# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:33:43+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import (
    Application,
    ApplicationCreated,
    Applications,
    FieldAppIdPutRequest,
    FieldDatamodelCodeGeneratorRootSpecialPostRequest,
)

app = MCPProxy(
    contact={
        'email': 'devrel@nexmo.com',
        'name': 'Nexmo.com',
        'url': 'https://developer.nexmo.com/',
        'x-twitter': 'Nexmo',
    },
    description='<div class="Vlt-callout Vlt-callout--critical"> <i></i> <div class="Vlt-callout__content">\n  <h4>Applications V1 is deprecated</h4>\n  This version of the API has been deprecated. Please use <a href="/api/application.v2">version 2</a> going forwards\n</div> </div>\nA Nexmo application contains the security and configuration information you need to connect to Nexmo endpoints and easily use our products.',
    license={
        'name': 'The MIT License (MIT)',
        'url': 'https://opensource.org/licenses/MIT',
    },
    termsOfService='https://www.nexmo.com/terms-of-use',
    title='Nexmo Application API',
    version='1.0.2',
    servers=[{'url': 'https://api.nexmo.com/v1/applications'}],
)


@app.get(
    '/#-datamodel-code-generator-#-root-#-special-#',
    description=""" You use a `GET` request to retrieve details of all applications associated with your account. """,
    tags=['application_crud_operations'],
)
def retrieve_applications(
    api_key: str,
    api_secret: str = ...,
    page_size: Optional[int] = 10,
    page_index: Optional[int] = 0,
):
    """
    Retrieve all Applications
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/#-datamodel-code-generator-#-root-#-special-#',
    description=""" You use a `POST` request to create a new application. """,
    tags=['application_crud_operations'],
)
def create_application(body: FieldDatamodelCodeGeneratorRootSpecialPostRequest = None):
    """
    Create Application
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/{app_id}',
    description=""" You use a `DELETE` request to delete a single application. """,
    tags=['application_crud_operations'],
)
def delete_application(app_id: str):
    """
    Destroy Application
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{app_id}',
    description=""" You use a `GET` request to retrieve details about a single application. """,
    tags=['application_crud_operations'],
)
def retrieve_application(api_key: str, api_secret: str = ..., app_id: str = ...):
    """
    Retrieve Application
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/{app_id}',
    description=""" You use a `PUT` request to update an existing application. """,
    tags=['application_crud_operations'],
)
def update_application(app_id: str, body: FieldAppIdPutRequest = None):
    """
    Update Application
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
