# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:33:43+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class ApiKey(RootModel[str]):
    root: str = Field(
        ...,
        description='You can find your API key in your [account overview](https://dashboard.nexmo.com/account-overview)',
        examples=['ap1k3y'],
    )


class ApiSecret(RootModel[str]):
    root: str = Field(
        ...,
        description='You can find your API secret in your [account overview](https://dashboard.nexmo.com/account-overview)',
        examples=['230e6cf0709417176df1b4fc1e083adc'],
    )


class ApplicationBase(BaseModel):
    id: Optional[str] = Field(
        None,
        description='The ID allocated to your application by Nexmo.',
        examples=['aaaaaaaa-bbbb-cccc-dddd-0123456789ab'],
    )
    name: Optional[str] = Field(
        None, description='The name of your application', examples=['My Application']
    )


class Keys(BaseModel):
    public_key: Optional[str] = Field(
        None,
        description='The public key used to validate the [JWT](https://en.wikipedia.org/wiki/JSON_Web_Token).',
        examples=['PUBLIC_KEY'],
    )


class KeysWithPrivateKey(Keys):
    private_key: Optional[str] = Field(
        None,
        description='The private key you use to generate the JSON Web Token (JWT) that authenticates your requests to Messages API.',
        examples=['PRIVATE_KEY'],
    )


class Links(BaseModel):
    href: Optional[str] = Field(
        None,
        description='The link URL.',
        examples=['/v1/applications/aaaaaaaa-bbbb-cccc-dddd-0123456789ab'],
    )


class EndpointType(Enum):
    inbound_url = 'inbound_url'
    status_url = 'status_url'


class HttpMethod(Enum):
    GET = 'GET'
    POST = 'POST'


class Webhook(BaseModel):
    endpoint: str = Field(
        ...,
        description='`inbound_url`: The URL where inbound messages are delivered. `status_url`: The URL where message status is delivered.',
        examples=['https://example.com/webhooks/status'],
    )
    endpoint_type: EndpointType = Field(..., examples=['status_url'])
    http_method: HttpMethod = Field(
        ...,
        description='The HTTP method used to send data to the `inbound_url` or `status_url`. Default is POST.',
        examples=['POST'],
    )


class Messages(BaseModel):
    webhooks: Optional[List[Webhook]] = None


class EndpointType1(Enum):
    answer_url = 'answer_url'
    event_url = 'event_url'


class Webhook1(BaseModel):
    endpoint: str = Field(
        ...,
        description='`answer_url`: The URL where your webhook delivers the Nexmo Call Control Object that governs this call. As soon as your user answers a call Nexmo makes a request to answer_url. `event_url`: Nexmo sends event information asynchronously to this URL when status changes.',
        examples=['https://example.com/webhooks/answer'],
    )
    endpoint_type: EndpointType1 = Field(..., examples=['answer_url'])
    http_method: HttpMethod = Field(
        ...,
        description='The HTTP method used to send event information to the `event_url` or `answer_url`.',
        examples=['GET'],
    )


class Voice(BaseModel):
    webhooks: Optional[List[Webhook1]] = None


class Type(Enum):
    voice = 'voice'
    messages = 'messages'


class FieldDatamodelCodeGeneratorRootSpecialPostRequest(BaseModel):
    answer_method: Optional[str] = Field(
        None,
        description='The HTTP method used to make the request to `answer_url`. The default value is `GET`.',
        examples=['GET'],
    )
    answer_url: Optional[str] = Field(
        None,
        description='The URL where your webhook delivers the Nexmo Call Control Object that governs this call. As soon as your user answers a call Nexmo makes a request to `answer_url`. Required for inbound calls only.',
        examples=['https://example.com/webhooks/answer'],
    )
    api_key: ApiKey
    api_secret: ApiSecret
    event_method: Optional[str] = Field(
        None,
        description='The HTTP method used to send event information to `event_url`. The default value is `POST`. For `voice` type applications only.',
        examples=['POST'],
    )
    event_url: Optional[str] = Field(
        None,
        description='Nexmo sends event information asynchronously to this URL when status changes for `voice` applications. Always required for `voice` applications.',
        examples=['https://example.com/webhooks/event'],
    )
    inbound_method: Optional[str] = Field(
        None,
        description='The HTTP method used to send event information to `inbound_url`. The default value is `POST`. For `messages` type applications only.',
        examples=['POST'],
    )
    inbound_url: Optional[str] = Field(
        None,
        description='Nexmo sends a request to this URL when an inbound message is received. Required for `messages` type applications only.',
        examples=['https://example.com/webhooks/inbound'],
    )
    name: str = Field(
        ..., description='The name of your application.', examples=['My Application']
    )
    status_method: Optional[str] = Field(
        None,
        description='The HTTP method used to send event information to `status_url`. The default value is `POST`. For `messages` type applications only.',
        examples=['POST'],
    )
    status_url: Optional[str] = Field(
        None,
        description='Nexmo sends event information asynchronously to this URL when status changes. Required for `messages` type applications only.',
        examples=['https://example.com/webhooks/status'],
    )
    type: Type = Field(
        ...,
        description='The Nexmo product or products that you access with this application. Currently `voice` and `messages` application types are supported.',
        examples=['voice'],
    )


class FieldAppIdPutRequest(BaseModel):
    answer_method: Optional[str] = Field(
        'GET',
        description='The HTTP method used to make the request to `answer_url`. The default value is `GET`.',
        examples=['GET'],
    )
    answer_url: Optional[str] = Field(
        None,
        description='The URL where your webhook delivers the Nexmo Call Control Object that governs this call. As soon as your user answers a call Nexmo makes a request to `answer_url`.',
        examples=['https://example.com/webhooks/answer'],
    )
    api_key: ApiKey
    api_secret: ApiSecret
    event_method: Optional[str] = Field(
        'POST',
        description='The HTTP method used to send event information to `event_url`. The default value is POST.',
        examples=['POST'],
    )
    event_url: Optional[str] = Field(
        None,
        description='Nexmo sends event information asynchronously to this URL when status changes.',
        examples=['https://example.com/webhooks/event'],
    )
    name: str = Field(
        ...,
        description='The name of your application.',
        examples=['UpdatedApplication'],
    )
    type: Type = Field(
        ...,
        description="The Nexmo product or products that you access with this application. Currently `voice` and `messages` application types are supported. You  can't change the type of application.",
        examples=['voice'],
    )


class Id(RootModel[str]):
    root: str = Field(
        ...,
        description='The ID allocated to your application by Nexmo.',
        examples=['aaaaaaaa-bbbb-cccc-dddd-0123456789ab'],
    )


class Name(RootModel[str]):
    root: str = Field(
        ..., description='The name of your application', examples=['My Application']
    )


class Count(RootModel[int]):
    root: int = Field(
        ...,
        description='The number of items associated with your account.',
        examples=[1],
    )


class PageIndex(RootModel[int]):
    root: int = Field(..., description='The offset from the first page.', examples=[1])


class PageSize(RootModel[int]):
    root: int = Field(
        ...,
        description='The number of items returned on each call to this endpoint. The default is 10 records.',
        examples=[10],
    )


class Application(BaseModel):
    field_links: Optional[Links] = Field(None, alias='_links')
    id: Optional[Id] = None
    keys: Optional[Keys] = None
    messages: Messages
    name: Name
    voice: Voice


class ApplicationCreated(Application):
    keys: Optional[KeysWithPrivateKey] = None


class FieldEmbedded(BaseModel):
    applications: Optional[List[Application]] = Field(
        None,
        description='The collection of your applications. Each object contains information about an an individual application. The public_key is not included in the application information.',
    )


class ApplicationsBase(BaseModel):
    field_embedded: Optional[FieldEmbedded] = Field(None, alias='_embedded')
    count: Optional[int] = Field(
        None,
        description='The number of items associated with your account.',
        examples=[1],
    )
    page_index: Optional[int] = Field(
        None, description='The offset from the first page.', examples=[1]
    )
    page_size: Optional[int] = Field(
        None,
        description='The number of items returned on each call to this endpoint. The default is 10 records.',
        examples=[10],
    )


class Applications(BaseModel):
    field_embedded: FieldEmbedded = Field(..., alias='_embedded')
    field_links: Links = Field(..., alias='_links')
    count: Count
    page_index: PageIndex
    page_size: PageSize
